[[redirects]]
    from = "/api/*"
    to = "https://api.sociiity.com/api/:splat"
    status = 200

[[redirects]]
    from = "/media/*"
    to = "https://api.sociiity.com/media/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200